// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGck3b5njuOnXgsnlEJ5c4hk2GgL8WJzQ',
    appId: '1:205621401825:android:e2709a33448395c9793fa0',
    messagingSenderId: '205621401825',
    projectId: 'axent-579ca',
    storageBucket: 'axent-579ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD7gTBJsN3uWgs3lP2WcPn73Cc6nPMeYY',
    appId: '1:205621401825:ios:f44d41d0a01998fc793fa0',
    messagingSenderId: '205621401825',
    projectId: 'axent-579ca',
    storageBucket: 'axent-579ca.firebasestorage.app',
    iosBundleId: 'com.example.fashionfrontend.helloWorld',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnOJf79hONDd_WEZsybufpzW1Z9sGzoXU',
    appId: '1:205621401825:web:2302157cbee6c47b793fa0',
    messagingSenderId: '205621401825',
    projectId: 'axent-579ca',
    authDomain: 'axent-579ca.firebaseapp.com',
    storageBucket: 'axent-579ca.firebasestorage.app',
    measurementId: 'G-D054844DCB',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBD7gTBJsN3uWgs3lP2WcPn73Cc6nPMeYY',
    appId: '1:205621401825:ios:7ff69bf5f699a701793fa0',
    messagingSenderId: '205621401825',
    projectId: 'axent-579ca',
    storageBucket: 'axent-579ca.firebasestorage.app',
    iosBundleId: 'com.example.fashionfrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnOJf79hONDd_WEZsybufpzW1Z9sGzoXU',
    appId: '1:205621401825:web:fe7b874b891a90ef793fa0',
    messagingSenderId: '205621401825',
    projectId: 'axent-579ca',
    authDomain: 'axent-579ca.firebaseapp.com',
    storageBucket: 'axent-579ca.firebasestorage.app',
    measurementId: 'G-1KFR33836E',
  );

}