# Generated by Django 4.2.19 on 2025-03-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_recommender', '0002_userpreference_userprofile_delete_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, upload_to='product_photos/'),
        ),
    ]
