# Generated by Django 4.2.19 on 2025-03-25 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_recommender', '0006_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photo',
        ),
    ]
