# Generated by Django 4.2.19 on 2025-04-10 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_recommender', '0008_remove_userprofile_user_delete_userpreference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.IntegerField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
