# Generated by Django 4.2.19 on 2025-04-17 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_recommender', '0010_alter_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.URLField(default='', max_length=500),
        ),
    ]
