# Generated by Django 4.2.19 on 2025-04-21 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_recommender', '0012_stockxtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockXSecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('id_token', models.TextField(blank=True, null=True)),
                ('expires_in', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='StockXToken',
        ),
    ]
