# Generated by Django 4.2.19 on 2025-04-21 20:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product_recommender', '0013_stockxsecret_delete_stockxtoken'),
    ]

    operations = [
        
    ]
