# Generated by Django 4.2.19 on 2025-04-21 20:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product_recommender', '0014_alter_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='uuid_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
