# Generated by Django 4.2.19 on 2025-04-21 21:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product_recommender', '0016_rename_category_product_product_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockxsecret',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
