# Generated by Django 4.2.19 on 2025-04-22 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_recommender', '0018_product_currency_product_highest_bid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockXSecret',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='product',
            name='highest_bid',
        ),
        migrations.RemoveField(
            model_name='product',
            name='lowest_ask',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='retail_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='season',
        ),
        migrations.RemoveField(
            model_name='product',
            name='style_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='url_key',
        ),
        migrations.AddField(
            model_name='product',
            name='estimatedMarketValue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='retailprice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='silhouette',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='story',
            field=models.TextField(blank=True, null=True),
        ),
    ]
