# Generated by Django 4.2.19 on 2025-04-22 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_recommender', '0019_delete_stockxsecret_remove_product_color_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='uuid',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product_recommender.product'),
        ),
    ]
