# Generated by Django 4.2.19 on 2025-04-22 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_recommender', '0021_alter_productimage_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
    ]
