# Generated by Django 4.2.19 on 2025-04-22 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_recommender', '0025_remove_product_url_product_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image_type',
            field=models.CharField(choices=[('360', '360 Image'), ('original', 'Original'), ('small', 'Small'), ('thumbnail', 'Thumbnail')], default='original', max_length=20),
        ),
    ]
