# Generated by Django 4.2.19 on 2025-04-22 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_recommender', '0026_productimage_image_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='urls',
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_type',
            field=models.CharField(default='original', max_length=20),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product_recommender.product'),
        ),
    ]
