# Generated by Django 4.2.19 on 2025-04-28 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_recommender', '0028_remove_product_image_url_product_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='store_links',
            field=models.JSONField(blank=True, default=dict, help_text='Dictionary of buy links for different platforms'),
        ),
    ]
