# Generated by Django 4.2.19 on 2025-04-28 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_recommender', '0029_product_store_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='store_links',
        ),
    ]
