# Generated by Django 4.2.19 on 2025-06-05 16:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product_recommender', '0031_alter_product_urls'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='silhouette',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='story',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='estimatedMarketValue',
        ),
        migrations.RemoveField(
            model_name='product',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='product',
            name='urls',
        ),
        migrations.AddField(
            model_name='product',
            name='link',
            field=models.URLField(blank=True, default='', help_text='Link to the product page'),
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='secondary_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='trait',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='upcoming',
            field=models.BooleanField(default=False, help_text='Indicates if the product is upcoming'),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='colorway',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.DecimalField(decimal_places=1, max_digits=3)),
                ('sizeMen', models.BooleanField(default=True)),
                ('lowest_ask', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_asks', models.IntegerField(default=0)),
                ('subtotal', models.JSONField(default=dict, help_text='Dictionary of shipping options and their prices')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product_recommender.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage360',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('order', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images360', to='product_recommender.product')),
            ],
        ),
    ]
