# Generated by Django 4.2.19 on 2025-06-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_recommender', '0032_rename_silhouette_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='newField',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Previous lowest ask price', max_digits=10, null=True),
        ),
    ]
