# Generated by Django 4.2.19 on 2025-06-05 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_recommender', '0034_rename_newfield_productvariant_previous_lowest_ask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='colorway',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='link',
        ),
        migrations.RemoveField(
            model_name='product',
            name='model',
        ),
        migrations.RemoveField(
            model_name='product',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='retailprice',
        ),
        migrations.RemoveField(
            model_name='product',
            name='secondary_category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
        migrations.RemoveField(
            model_name='product',
            name='trait',
        ),
        migrations.RemoveField(
            model_name='product',
            name='upcoming',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
    ]
