# Generated by Django 4.2.19 on 2025-06-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_recommender', '0036_product_brand_product_category_product_colorway_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='Unique slug for the product', max_length=200, null=True, unique=True),
        ),
    ]
