# Generated by Django 4.2.19 on 2025-06-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_recommender', '0039_alter_product_link_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='productimage360',
            name='image_url',
            field=models.URLField(max_length=500),
        ),
    ]
