# Generated by Django 4.2.19 on 2025-06-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_recommender', '0041_productvariant_sizeyouth'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='sizeKids',
            field=models.BooleanField(default=False),
        ),
    ]
