# Generated by Django 4.2.19 on 2025-06-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_recommender', '0042_productvariant_sizekids'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='normalized_colorway',
            field=models.JSONField(default=list),
        ),
    ]
