# Generated by Django 4.2.19 on 2025-06-15 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_recommender', '0043_product_normalized_colorway'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='sizeKids',
            new_name='isKids',
        ),
        migrations.RenameField(
            model_name='productvariant',
            old_name='sizeMen',
            new_name='isMen',
        ),
        migrations.RenameField(
            model_name='productvariant',
            old_name='sizeYouth',
            new_name='isYouth',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='isWomen',
            field=models.BooleanField(default=False),
        ),
    ]
