# Generated by Django 4.2.19 on 2025-07-14 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_recommender', '0044_rename_sizekids_productvariant_iskids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.URLField(default='', max_length=500),
        ),
    ]
