# Generated by Django 4.2.19 on 2025-07-15 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_recommender', '0045_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='imageURL',
        ),
    ]
