# Generated by Django 4.2.19 on 2025-04-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_recommender', '0010_alter_product_id'),
        ('user_preferences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='liked_products',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='product_recommender.product'),
        ),
    ]
