# Generated by Django 4.2.19 on 2025-04-15 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_preferences', '0002_userprofile_liked_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='firebase_uid',
            field=models.CharField(default=0, max_length=256, unique=True),
            preserve_default=False,
        ),
    ]
