# Generated by Django 4.2.19 on 2025-04-23 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_preferences', '0004_remove_userprofile_user_userprofile_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='preferences',
        ),
    ]
