# Generated by Django 4.2.19 on 2025-06-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_recommender', '0032_rename_silhouette_product_category_and_more'),
        ('user_preferences', '0005_remove_userprofile_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bought_products',
            field=models.ManyToManyField(blank=True, related_name='bought_by', to='product_recommender.product'),
        ),
    ]
