# Generated by Django 4.2.19 on 2025-06-30 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wardrobe',
            name='product_ids',
            field=models.JSONField(default=list),
        ),
    ]
