# Generated by Django 4.2.19 on 2025-07-01 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobes', '0002_wardrobe_product_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wardrobeitem',
            name='wardrobe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wardrobes.wardrobe'),
        ),
    ]
