# Generated by Django 4.2.19 on 2025-07-01 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobes', '0003_alter_wardrobeitem_wardrobe'),
        ('wardrobes', '0003_wardrobeitem_related_name'),
    ]

    operations = [
    ]
